version: '3'

services:
  postgres:
    container_name: 'nestjs-postgres'
    image: 'postgres'
    env_file:
      - docker.env
    ports:
      - '5433:5433'
    command: -p 5433
    volumes:
      - /data/postgres:/data/postgres
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
